#!/usr/bin/env bash
# =============================================================================
# RaBbLE-Grimoire — graph-grimoire.sh
# Builds a documentation graph — nodes are .md files, edges are markdown links.
# Outputs JSON adjacency list and Mermaid diagram. Reports orphans and hubs.
#
# Usage:
#   bash spells/graph-grimoire.sh              # full graph + summary
#   bash spells/graph-grimoire.sh --json-only  # just write JSON, skip mermaid
#
# spark ~ grimoire >> the nervous system mapped // %DOC_GRAPH%
# =============================================================================

set -euo pipefail

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  echo "graph-grimoire.sh — build a documentation link graph of the Grimoire"
  echo ""
  echo "Usage: bash spells/graph-grimoire.sh [--json-only]"
  echo "  --json-only   Write JSON graph only, skip Mermaid diagram"
  echo ""
  echo "Outputs:"
  echo "  log/grimoire-graph.json   — adjacency list (nodes + edges)"
  echo "  log/grimoire-graph.md     — Mermaid diagram (renderable in GitHub/Obsidian)"
  echo ""
  echo "Reports: orphan docs, hub docs, islands, link density."
  exit 0
fi

GRIMOIRE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
JSON_ONLY="${1:-}"

MAGENTA='\033[38;2;255;45;120m'
CYAN='\033[38;2;0;245;255m'
GREEN='\033[38;2;80;250;123m'
YELLOW='\033[38;2;241;250;140m'
RED='\033[38;2;224;92;111m'
MUTED='\033[38;2;107;104;128m'
RESET='\033[0m'

mkdir -p "$GRIMOIRE_ROOT/log"

GRAPH_JSON="$GRIMOIRE_ROOT/log/grimoire-graph.json"
GRAPH_MD="$GRIMOIRE_ROOT/log/grimoire-graph.md"

declare -A NODE_DIR
declare -A OUTGOING
declare -A INCOMING

# Collect all .md files as nodes
while IFS= read -r filepath; do
  rel="${filepath#$GRIMOIRE_ROOT/}"
  dir="${rel%%/*}"
  [[ "$dir" == "$rel" ]] && dir="root"
  NODE_DIR["$rel"]="$dir"
  OUTGOING["$rel"]=0
  INCOMING["$rel"]=0
done < <(find "$GRIMOIRE_ROOT" -name '*.md' -type f ! -path '*/log/grimoire-graph.md' | sort)

EDGES=()

# Extract links from each file
for rel in "${!NODE_DIR[@]}"; do
  filepath="$GRIMOIRE_ROOT/$rel"
  filedir=$(dirname "$rel")

  while IFS= read -r link; do
    # Skip URLs, anchors, images
    [[ "$link" == http* ]] && continue
    [[ "$link" == \#* ]] && continue
    [[ "$link" == mailto:* ]] && continue

    # Strip anchor fragment
    link="${link%%#*}"
    # Strip query string
    link="${link%%\?*}"
    [[ -z "$link" ]] && continue

    # Resolve relative path
    if [[ "$link" == /* ]]; then
      resolved="${link#/}"
    else
      resolved=$(cd "$GRIMOIRE_ROOT/$filedir" 2>/dev/null && realpath -m --relative-to="$GRIMOIRE_ROOT" "$link" 2>/dev/null || echo "")
    fi
    [[ -z "$resolved" ]] && continue

    # Only count links to files that exist in our node set
    if [[ -n "${NODE_DIR[$resolved]:-}" ]]; then
      EDGES+=("$rel|$resolved")
      OUTGOING["$rel"]=$(( ${OUTGOING["$rel"]} + 1 ))
      INCOMING["$resolved"]=$(( ${INCOMING["$resolved"]} + 1 ))
    fi
  done < <(grep -oP '\]\(\K[^)]+' "$filepath" 2>/dev/null || true)
done

total_nodes=${#NODE_DIR[@]}
total_edges=${#EDGES[@]}

# --- Write JSON ---
{
  echo '{'
  echo '  "generated": "'$(date -Iseconds)'",'
  echo '  "total_nodes": '$total_nodes','
  echo '  "total_edges": '$total_edges','

  # Nodes
  echo '  "nodes": ['
  first=true
  for rel in $(echo "${!NODE_DIR[@]}" | tr ' ' '\n' | sort); do
    dir="${NODE_DIR[$rel]}"
    out="${OUTGOING[$rel]}"
    inc="${INCOMING[$rel]}"
    $first || echo ','
    printf '    {"id": "%s", "dir": "%s", "outgoing": %d, "incoming": %d}' "$rel" "$dir" "$out" "$inc"
    first=false
  done
  echo ''
  echo '  ],'

  # Edges
  echo '  "edges": ['
  first=true
  for edge in "${EDGES[@]}"; do
    from="${edge%%|*}"
    to="${edge#*|}"
    $first || echo ','
    printf '    {"from": "%s", "to": "%s"}' "$from" "$to"
    first=false
  done
  echo ''
  echo '  ]'
  echo '}'
} > "$GRAPH_JSON"

echo -e "${GREEN}Wrote${RESET} $GRAPH_JSON"

# --- Write Mermaid ---
if [[ "$JSON_ONLY" != "--json-only" ]]; then
  {
    echo '# Grimoire Documentation Graph'
    echo ''
    echo '> Auto-generated by `bash spells/graph-grimoire.sh` — do not edit.'
    echo "> Generated: $(date -Iseconds)"
    echo ''
    echo '```mermaid'
    echo 'graph LR'

    # Collect directories for subgraphs
    declare -A DIRS
    for rel in "${!NODE_DIR[@]}"; do
      DIRS["${NODE_DIR[$rel]}"]=1
    done

    # Abbreviate node IDs for mermaid readability
    abbrev() {
      local f="$1"
      # Strip .md extension, replace / and - with _
      echo "$f" | sed 's/\.md$//' | sed 's/[\/\-\.]/_/g' | sed 's/RaBbLE_//g'
    }

    label() {
      basename "$1" .md
    }

    for dir in $(echo "${!DIRS[@]}" | tr ' ' '\n' | sort); do
      echo "  subgraph ${dir}"
      for rel in $(echo "${!NODE_DIR[@]}" | tr ' ' '\n' | sort); do
        [[ "${NODE_DIR[$rel]}" == "$dir" ]] || continue
        echo "    $(abbrev "$rel")[\"$(label "$rel")\"]"
      done
      echo "  end"
    done

    # Edges
    for edge in "${EDGES[@]}"; do
      from="${edge%%|*}"
      to="${edge#*|}"
      echo "  $(abbrev "$from") --> $(abbrev "$to")"
    done

    echo '```'
    echo ''
    echo "**Nodes:** $total_nodes | **Edges:** $total_edges | **Avg links/doc:** $(echo "scale=1; $total_edges / $total_nodes" | bc 2>/dev/null || echo "?")"
  } > "$GRAPH_MD"

  echo -e "${GREEN}Wrote${RESET} $GRAPH_MD"
fi

# --- Summary ---
echo ""
echo -e "${MAGENTA}RaBbLE-Grimoire — Documentation Graph${RESET}"
echo -e "${MAGENTA}════════════════════════════════════════════════════════${RESET}"
printf "  ${CYAN}%-30s${RESET} %d\n" "Total documents" "$total_nodes"
printf "  ${CYAN}%-30s${RESET} %d\n" "Total links" "$total_edges"
if [[ $total_nodes -gt 0 ]]; then
  avg=$(echo "scale=1; $total_edges / $total_nodes" | bc 2>/dev/null || echo "?")
  printf "  ${CYAN}%-30s${RESET} %s\n" "Avg links per doc" "$avg"
fi

# Orphans (no incoming links, not INDEX.md)
echo ""
echo -e "${YELLOW}Orphan docs (no incoming links):${RESET}"
orphan_count=0
for rel in $(echo "${!NODE_DIR[@]}" | tr ' ' '\n' | sort); do
  if [[ "${INCOMING[$rel]}" -eq 0 && "$rel" != "INDEX.md" ]]; then
    echo -e "  ${MUTED}$rel${RESET}"
    ((orphan_count++)) || true
  fi
done
[[ $orphan_count -eq 0 ]] && echo -e "  ${GREEN}None${RESET}"

# Hub docs (>5 incoming)
echo ""
echo -e "${CYAN}Hub docs (>5 incoming links):${RESET}"
hub_count=0
for rel in $(echo "${!NODE_DIR[@]}" | tr ' ' '\n' | sort); do
  if [[ "${INCOMING[$rel]}" -gt 5 ]]; then
    echo -e "  ${GREEN}$rel${RESET} (${INCOMING[$rel]} incoming)"
    ((hub_count++)) || true
  fi
done
[[ $hub_count -eq 0 ]] && echo -e "  ${MUTED}None${RESET}"

# Islands (no incoming AND no outgoing)
echo ""
echo -e "${RED}Islands (no links at all):${RESET}"
island_count=0
for rel in $(echo "${!NODE_DIR[@]}" | tr ' ' '\n' | sort); do
  if [[ "${INCOMING[$rel]}" -eq 0 && "${OUTGOING[$rel]}" -eq 0 ]]; then
    echo -e "  ${RED}$rel${RESET}"
    ((island_count++)) || true
  fi
done
[[ $island_count -eq 0 ]] && echo -e "  ${GREEN}None${RESET}"

echo ""
echo -e "${MUTED}Mermaid graph: log/grimoire-graph.md (paste into GitHub/Obsidian to render)${RESET}"
echo -e "${MUTED}JSON graph:    log/grimoire-graph.json${RESET}"
echo ""
